---
# can be debug or production
env: "debug"

orchestrator: "127.0.0.1:8082"
listen: ":8081"
# every 10 seconds (in millisecond)
heartbeat_every: 10000

log_file: "debug.log"
# log_level: "trace"
log_level: "debug"

use_syslog: false
syslog_socket_type: "udp"
syslog_address: "localhost:514"
syslog_tag: ""
syslog_facility: "local7"
syslog_level: "debug"
